In [1]:
import pandas as pd
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [3]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [4]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [5]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

params_grid={'max_features':['sqrt', 'log2'],'n_estimators': [50, 100, 200],
    'max_depth': [10, 20],'criterion':['gini', 'entropy','log_loss']}

grid=GridSearchCV(RandomForestClassifier(),params_grid,refit=True,scoring='f1',verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
60 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\ensemble\_forest.py", line 467, in fit
    for i, t in enumerate(trees)
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\joblib\parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\joblib\parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\joblib\parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\joblib\parallel.py", line 264, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\joblib\parallel.py", line 264, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\fixes.py", line 216, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\ensemble\_forest.py", line 185, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.9742116  0.97711131 0.98267232 0.98284664 0.9800087  0.98541097
 0.98284781 0.98267232 0.97961504 0.98583384 0.97977493 0.98848384
 0.97711015 0.97950633 0.97950633 0.98583161 0.98018418 0.9800087
 0.97711131 0.98541097 0.98267232 0.97977493 0.98574519 0.98308157
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,
C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [10, 20],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [50, 100, 200]},
             scoring='f1', verbose=3)

In [14]:
result=grid.cv_results_
print(result)

{'mean_fit_time': array([0.26239824, 0.39326458, 0.67256269, 0.17891526, 0.33207259,
       0.85304408, 0.17084284, 0.34549837, 0.6921164 , 0.1857513 ,
       0.41781521, 0.85366149, 0.17758312, 0.40315824, 0.69913249,
       0.18397946, 0.35516429, 0.66233859, 0.18078232, 0.33596907,
       0.67499595, 0.17737603, 0.34179382, 0.6848928 , 0.06561995,
       0.11683269, 0.22895956, 0.06874433, 0.12441082, 0.21749148,
       0.07567806, 0.11206226, 0.22327876, 0.06828437, 0.12431283,
       0.19471903]), 'std_fit_time': array([0.0335848 , 0.03545593, 0.01865333, 0.00787772, 0.01456904,
       0.09214615, 0.00151801, 0.01152   , 0.01144512, 0.00604877,
       0.03306661, 0.07115753, 0.00319998, 0.02705293, 0.02061238,
       0.01012331, 0.00640047, 0.01781508, 0.01085145, 0.00876262,
       0.01202602, 0.00468401, 0.00591922, 0.04068967, 0.00624919,
       0.00803455, 0.00986477, 0.00765374, 0.00715096, 0.00859011,
       0.00511536, 0.00651797, 0.02356494, 0.00709044, 0.00367909,
       0.02595335]), 'mean_score_time': array([0.02463508, 0.03796883, 0.0564589 , 0.01874919, 0.02812276,
       0.06675849, 0.01562562, 0.03109303, 0.05312138, 0.01529579,
       0.03904748, 0.05919499, 0.01599827, 0.03520288, 0.0671937 ,
       0.01919894, 0.02879796, 0.05599537, 0.01759839, 0.03199735,
       0.05227027, 0.02209468, 0.03134289, 0.05267606, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ]), 'std_score_time': array([9.66112919e-03, 4.43479418e-03, 5.79908976e-03, 6.24921325e-03,
       6.24935629e-03, 1.90099446e-02, 2.67878950e-06, 4.28306001e-03,
       7.65440239e-03, 1.22725442e-03, 6.71224236e-03, 3.91938622e-03,
       8.34124359e-07, 3.92614123e-03, 1.08513984e-02, 3.91921101e-03,
       3.91903588e-03, 5.05972992e-03, 3.20017342e-03, 5.05972992e-03,
       6.06765548e-03, 7.48516427e-03, 1.89590874e-04, 6.45015328e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]), 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                   'gini', 'gini', 'gini', 'gini', 'gini', 'entropy',
                   'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                   'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                   'entropy', 'log_loss', 'log_loss', 'log_loss',
                   'log_loss', 'log_loss', 'log_loss', 'log_loss',
                   'log_loss', 'log_loss', 'log_loss', 'log_loss',
                   'log_loss'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_depth': masked_array(data=[10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 10, 10,
                   10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 10, 10, 10, 10,
                   10, 10, 20, 20, 20, 20, 20, 20],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'log2', 'log2', 'log2', 'sqrt',
                   'sqrt', 'sqrt', 'log2', 'log2', 'log2', 'sqrt', 'sqrt',
                   'sqrt', 'log2', 'log2', 'log2', 'sqrt', 'sqrt', 'sqrt',
                   'log2', 'log2', 'log2', 'sqrt', 'sqrt', 'sqrt', 'log2',
                   'log2', 'log2', 'sqrt', 'sqrt', 'sqrt', 'log2', 'log2',
                   'log2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_n_estimators': masked_array(data=[50, 100, 200, 50, 100, 200, 50, 100, 200, 50, 100, 200,
                   50, 100, 200, 50, 100, 200, 50, 100, 200, 50, 100, 200,
                   50, 100, 200, 50, 100, 200, 50, 100, 200, 50, 100, 200],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 50}, {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 200}, {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 50}, {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 200}, {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 50}, {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 200}, {'criterion': 'gini', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 50}, {'criterion': 'gini', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'gini', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 200}, {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 50}, {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 200}, {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 50}, {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 200}, {'criterion': 'entropy', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 50}, {'criterion': 'entropy', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'entropy', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 200}, {'criterion': 'entropy', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 50}, {'criterion': 'entropy', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'entropy', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 200}, {'criterion': 'log_loss', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 50}, {'criterion': 'log_loss', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'log_loss', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 200}, {'criterion': 'log_loss', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 50}, {'criterion': 'log_loss', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'log_loss', 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 200}, {'criterion': 'log_loss', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 50}, {'criterion': 'log_loss', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'log_loss', 'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 200}, {'criterion': 'log_loss', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 50}, {'criterion': 'log_loss', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'log_loss', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 200}], 'split0_test_score': array([0.98550725, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan]), 'split1_test_score': array([0.95890411, 0.95890411, 0.97222222, 0.97222222, 0.95890411,
       0.98591549, 0.97222222, 0.97222222, 0.98591549, 0.95774648,
       0.97222222, 0.98591549, 0.95890411, 0.97222222, 0.97222222,
       0.97222222, 0.95890411, 0.95890411, 0.95890411, 0.98591549,
       0.97222222, 0.97222222, 0.97222222, 0.95890411,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan]), 'split2_test_score': array([0.95522388, 0.95522388, 0.95522388, 0.97058824, 0.95522388,
       0.95522388, 0.97058824, 0.95522388, 0.95522388, 0.98550725,
       0.95522388, 0.97058824, 0.95522388, 0.93939394, 0.93939394,
       0.98550725, 0.97058824, 0.95522388, 0.95522388, 0.95522388,
       0.95522388, 0.95522388, 0.97058824, 0.97058824,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan]), 'split3_test_score': array([0.98591549, 0.97142857, 0.98591549, 0.98591549, 0.98591549,
       0.98591549, 0.97142857, 0.98591549, 0.97142857, 0.98591549,
       0.97142857, 0.98591549, 0.98591549, 0.98591549, 0.98591549,
       0.97142857, 0.97142857, 0.98591549, 0.97142857, 0.98591549,
       0.98591549, 0.97142857, 0.98591549, 0.98591549,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan]), 'split4_test_score': array([0.98550725, 1.        , 1.        , 0.98550725, 1.        ,
       1.        , 1.        , 1.        , 0.98550725, 1.        ,
       1.        , 1.        , 0.98550725, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan]), 'mean_test_score': array([0.9742116 , 0.97711131, 0.98267232, 0.98284664, 0.9800087 ,
       0.98541097, 0.98284781, 0.98267232, 0.97961504, 0.98583384,
       0.97977493, 0.98848384, 0.97711015, 0.97950633, 0.97950633,
       0.98583161, 0.98018418, 0.9800087 , 0.97711131, 0.98541097,
       0.98267232, 0.97977493, 0.98574519, 0.98308157,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan]), 'std_test_score': array([0.01405003, 0.01944551, 0.01716762, 0.01071337, 0.0194622 ,
       0.01635512, 0.01401424, 0.01716762, 0.01517832, 0.01542967,
       0.01759299, 0.01094248, 0.01721894, 0.0225527 , 0.0225527 ,
       0.01260361, 0.01677449, 0.0194622 , 0.01944551, 0.01635512,
       0.01716762, 0.01759299, 0.01279869, 0.01625503,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan]), 'rank_test_score': array([24, 21, 10,  9, 14,  5,  8, 10, 18,  2, 16,  1, 23, 19, 19,  3, 13,
       14, 21,  5, 10, 16,  4,  7, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])}

In [15]:
y_pred=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[44  1]
 [ 1 74]]

In [16]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        45
           1       0.99      0.99      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

In [17]:
print(grid.best_params_)

{'criterion': 'gini', 'max_depth': 20, 'max_features': 'log2', 'n_estimators': 200}

In [18]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [20]:
grid.predict([[12,120,1,100,10,10,120,23,23,3,1,34,21,12,34,0,0,9,0,0,0,0,0,1,1,1,1]])

C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

array([1], dtype=uint8)